// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6pxDR_Pb0MDMwTxm2igYbSYcXfGbvlcY',
    appId: '1:852328484281:web:25ade2a5c764acb7f5fa68',
    messagingSenderId: '852328484281',
    projectId: 'getshoes-dc0f6',
    authDomain: 'getshoes-dc0f6.firebaseapp.com',
    storageBucket: 'getshoes-dc0f6.appspot.com',
    measurementId: 'G-6C9V607L0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoObY2KfjOPwOyKC9Hvtyvq3o5OD_G2k',
    appId: '1:852328484281:android:c9d4ac2b1c91fbaaf5fa68',
    messagingSenderId: '852328484281',
    projectId: 'getshoes-dc0f6',
    storageBucket: 'getshoes-dc0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_UBcYkjfHC3Rz5uPvlrBqAhoEihwGnBc',
    appId: '1:852328484281:ios:8c0d4315cf38a5a3f5fa68',
    messagingSenderId: '852328484281',
    projectId: 'getshoes-dc0f6',
    storageBucket: 'getshoes-dc0f6.appspot.com',
    iosBundleId: 'com.example.getShoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_UBcYkjfHC3Rz5uPvlrBqAhoEihwGnBc',
    appId: '1:852328484281:ios:8c0d4315cf38a5a3f5fa68',
    messagingSenderId: '852328484281',
    projectId: 'getshoes-dc0f6',
    storageBucket: 'getshoes-dc0f6.appspot.com',
    iosBundleId: 'com.example.getShoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6pxDR_Pb0MDMwTxm2igYbSYcXfGbvlcY',
    appId: '1:852328484281:web:1f1845a118b64062f5fa68',
    messagingSenderId: '852328484281',
    projectId: 'getshoes-dc0f6',
    authDomain: 'getshoes-dc0f6.firebaseapp.com',
    storageBucket: 'getshoes-dc0f6.appspot.com',
    measurementId: 'G-BDHKPK1FZY',
  );
}
